#!/bin/bash
MACRO_NAME="__BASE64DATA_$1"

function __wrap()
{
	while [ true ]
	do
		read line
		if [ $? -ne 0 ]; then
			exit 0
		fi
		echo -e "\t\t\"$line\"\\"
	done
}

cat << EOF
/* This file is generated by "__gen_base64_fonts.sh", part of danu_omxplayer
* Use the script if you are to update the data, not manually.
*/
#ifndef $MACRO_NAME
#	define $MACRO_NAME \\
EOF

base64 "$2" | __wrap

cat << EOF

#endif
EOF

